service: acceptessa2-circle-api-register
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-northeast-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action: [dynamodb:GetItem, dynamodb:PutItem, dynamodb:DeleteItem]
          Resource: { Fn::GetAtt: [RegisterTable, Arn] }

functions:
  validate:
    handler: handler.validate_mail
    events:
      - httpApi:
          path: /validate
          method: get

  check:
    handler: handler.check_mail
    events:
      - httpApi:
          path: /check
          method: get

resources:
  Resources:
    RegisterTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: acceptessa2-circle-register
        AttributeDefinitions:
          - { AttributeName: token, AttributeType: S }
        KeySchema:
          - { AttributeName: token, KeyType: HASH }
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
